# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\C Projects\My-Github\computer-vision-project\UI\About.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 410)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(540, 410))
        Dialog.setMaximumSize(QtCore.QSize(540, 410))
        Dialog.setWindowIcon(QtGui.QIcon('Icons//004-about.png'))
        Dialog.setStyleSheet("background-color: rgb(34, 34, 51);")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 90, 230, 230))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setPixmap(QtGui.QPixmap(
            "e:\\C Projects\\My-Github\\computer-vision-project\\UI\\../Icons/000-code.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(205, 10, 145, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(170, 204, 255);")
        self.label_9.setObjectName("label_9")
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setGeometry(QtCore.QRect(15, 40, 240, 351))
        self.splitter_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setOpaqueResize(True)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_16 = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_6 = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edge Detection | About"))
        self.label_9.setText(_translate(
            "Dialog", "<html><head/><body><p><span style=\" color:#7289ab;\">Edge Detection</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#7890b4;\">Technologies </span><span style=\" font-weight:600; color:#7289ab;\">used</span></p><p align=\"center\"><span style=\" font-style:italic; color:#aaccff;\">- Python</span></p><p align=\"center\"><span style=\" font-style:italic; color:#aaccff;\">- PyQt5 Library</span></p><p align=\"center\"><span style=\" font-style:italic; color:#aaccff;\">- Qt Designer</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#7289ab;\">Project Advisors</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#aaccff;\">- Dr. Mohamed Abdel-Hameid</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#aaccff;\">- Dr. Safynaz Abdel-Fattah</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#7289ab;\">Created by</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#aaccff;\">- Abdelrahman Mahmoud</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#aaccff;\">- Ali Abdallah</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#aaccff;\">- Taha Mahmoud</span></p></body></html>"))
